export default {
    STEP_KEYS: {
        START: "START",
        FINANCIAL: "FINANCIAL_VERIFICATION",
        EMPLOYMENT: "EMPLOYMENT_VERIFICATION",
        QUESTIONS: "QUESTIONS",
        APPLICANTS: "APPLICANTS",
        IDENTITY: "IDENTITY_VERIFICATION",
    }
};
