#!/usr/bin/env node
/**
 * Consolidate AI-Generated Documentation
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BATCHES_DIR = path.join(__dirname, '../../documentation/batches');
const OUTPUT_FILE = path.join(__dirname, '../../documentation/CONSOLIDATED_DOCUMENTATION.md');

async function main() {
    console.log('📚 Consolidating AI documentation...');
    
    if (!fs.existsSync(BATCHES_DIR)) {
        console.error(`❌ Batches dir not found`);
        process.exit(1);
    }
    
    const batchFiles = fs.readdirSync(BATCHES_DIR)
        .filter(f => f.startsWith('batch-') && f.endsWith('.json'))
        .sort();
    
    console.log(`✅ Found ${batchFiles.length} batches`);
    
    const allEntries = [];
    
    for (const file of batchFiles) {
        const data = JSON.parse(fs.readFileSync(path.join(BATCHES_DIR, file), 'utf-8'));
        const entries = data.entries || data; // Support both formats
        const markdowns = Array.isArray(entries) ? entries.map(e => e.markdown || e).filter(Boolean) : [];
        allEntries.push(...markdowns);
        console.log(`   📦 ${file}: ${markdowns.length} entries`);
    }
    
    // Get generator name from environment or default
    const generatedBy = process.env.GIT_USER_NAME || process.env.GITHUB_ACTOR || 'Automated Workflow';
    const currentDate = new Date().toISOString().split('T')[0]; // YYYY-MM-DD format
    
    const header = `# UI Test Documentation

## 📚 Test Documentation

> **Generated:** ${currentDate}  
> **Total Tests:** ${allEntries.length}  
> **Generated by:** ${generatedBy}

---

`;
    
    const footer = `\n\n---\n\n_Last Updated: ${new Date().toLocaleString('en-US', { timeZone: 'UTC', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })} UTC_\n`;
    
    fs.writeFileSync(OUTPUT_FILE, header + allEntries.join('\n\n') + footer);
    
    console.log(`\n✅ Consolidated ${allEntries.length} entries`);
    console.log(`##CONSOLIDATE_STATS_START##`);
    console.log(`TOTAL_ENTRIES:${allEntries.length}`);
    console.log(`BATCHES_PROCESSED:${batchFiles.length}`);
    console.log(`##CONSOLIDATE_STATS_END##`);
}

main().catch(e => {
    console.error('❌', e);
    process.exit(1);
});

