name: Staging Regression Tests

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  NODE_ENV: test
  CI: true

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Install trcli
        if: always()
        run: |
          echo "Installing trcli..."
          pip install trcli
          echo "✅ trcli installation completed"
          which trcli || echo "❌ trcli not found in PATH"

      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "APP_ENV=staging" >> $GITHUB_ENV
            echo "APP_URL=${{ vars.STAGING_APP_URL || 'https://staging.verifast.app' }}" >> $GITHUB_ENV
            echo "API_URL=${{ vars.STAGING_API_URL || 'https://api-staging.verifast.app' }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
            echo "APP_ENV=production" >> $GITHUB_ENV
            echo "APP_URL=${{ vars.PROD_APP_URL || 'https://verifast.app' }}" >> $GITHUB_ENV
            echo "API_URL=${{ vars.PROD_API_URL || 'https://api.verifast.app' }}" >> $GITHUB_ENV
          fi

      - name: Run regression tests
        run: |
          echo "🧪 Starting regression tests..."
          echo "📊 Running 4 specific tests:"
          echo "  - user-permission-verify.test.js"
          echo "  - skip_button_visibility_logic.spec.js" 
          echo "  - frontend_heartbeat.spec.js"
          echo "  - employment_skip_household_not_hidden_employment_connect.spec.js"
          echo "🌐 Environment: $APP_ENV"
          echo "🔗 Base URL: $APP_URL"
          echo ""
          npx playwright test --project=chromium tests/user-permission-verify.test.js tests/skip_button_visibility_logic.spec.js tests/frontend_heartbeat.spec.js tests/employment_skip_household_not_hidden_employment_connect.spec.js
          
          echo "📁 Checking generated files:"
          ls -la playwright-report/ || echo "playwright-report/ directory not found"
          find . -name "*.xml" -type f || echo "No XML files found"
        env:
          APP_ENV: ${{ env.APP_ENV }}
          APP_URL: ${{ env.APP_URL }}
          API_URL: ${{ env.API_URL }}
          TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
          TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
          TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ env.APP_ENV }}
          path: |
            playwright-report/
            test-results/
          retention-days: 30

      - name: Create TestRail test run
        if: always()
        run: |
          # Generate TestRail test run title with current date
          TEST_RUN_TITLE="Automated regression in: ${{ env.APP_ENV }} - Browser: chromium - Date $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          
          # Create TestRail test run and upload results
          TESTRAIL_OUTPUT=$(trcli -y \
            -h $TESTRAIL_HOST \
            --project "$TESTRAIL_PROJECT_NAME" \
            --username $TESTRAIL_USER \
            --key $TESTRAIL_API_KEY \
            parse_junit \
            --title "$TEST_RUN_TITLE" \
            --suite-id $TESTRAIL_SUITE_ID \
            --case-matcher "name" \
            --case-fields "custom_environment:${{ env.APP_ENV }}" \
            --result-fields "custom_browser:chromium" \
            --file playwright-report/results.xml 2>&1)
          
          echo "TestRail Output: $TESTRAIL_OUTPUT"
          
          # Extract TestRail run ID from output
          TESTRAIL_RUN_ID=$(echo "$TESTRAIL_OUTPUT" | grep -o "Test run: .*/runs/view/[0-9]*" | head -1 | sed 's/.*\/runs\/view\///')
          if [ -n "$TESTRAIL_RUN_ID" ]; then
            echo "TESTRAIL_RUN_ID=$TESTRAIL_RUN_ID" >> $GITHUB_ENV
            echo "✅ TestRail run created with ID: $TESTRAIL_RUN_ID"
          else
            echo "❌ Could not extract TestRail run ID"
            echo "TESTRAIL_RUN_ID=" >> $GITHUB_ENV
          fi
        env:
          TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
          TESTRAIL_PROJECT_NAME: ${{ secrets.TESTRAIL_PROJECT_NAME }}
          TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}

      - name: Process failed test videos
        if: always()
        run: |
          echo "🎥 Processing failed test videos..."
          if [ -d "test-results" ]; then
            echo "Found test-results directory, processing videos..."
            node scripts/testrail-integration.js attach-videos "${{ env.TESTRAIL_RUN_ID }}"
          else
            echo "No test-results directory found, skipping video processing"
          fi
        env:
          TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
          TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
          TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}

      - name: Create public report
        if: always()
        run: |
          echo "🔗 Creating public report..."
          if [ -n "${{ env.TESTRAIL_RUN_ID }}" ]; then
            PUBLIC_REPORT=$(node scripts/create-public-report.js "${{ env.TESTRAIL_RUN_ID }}" --save)
            echo "PUBLIC_REPORT_URL=$(echo "$PUBLIC_REPORT" | grep -o 'https://[^[:space:]]*')" >> $GITHUB_ENV
            echo "✅ Public report created"
          else
            echo "⚠️ No TestRail run ID available, skipping public report creation"
          fi
        env:
          TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
          TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
          TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}

      - name: Analyze flaky tests
        if: always()
        run: |
          echo "🔍 Analyzing test results for flakiness..."
          node scripts/flaky_analysis/flaky-test-analyzer.js "playwright-report/results.xml" "flaky-analysis.json" "20" "2"
          echo "📊 Flaky analysis completed"
          
          # Tag flaky tests if any found
          if [ -f "flaky-analysis.json" ]; then
            echo "🏷️ Checking for flaky tests to tag..."
            node scripts/flaky_analysis/flaky-test-tagger.js tag "flaky-analysis.json" "tests"
          fi
          
          echo "✅ Flaky test analysis and tagging completed"

      - name: Send Slack notification
        if: always()
        run: |
          echo "📤 Sending Slack notification..."
          node scripts/slack-notification.js "Staging Regression Tests" "${{ env.APP_ENV }}" "${{ github.run_id }}" "playwright-report/results.xml" "${{ env.TESTRAIL_RUN_ID }}" "${{ env.PUBLIC_REPORT_URL }}" "flaky-analysis.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
          TESTRAIL_PROJECT_NAME: ${{ secrets.TESTRAIL_PROJECT_NAME }}
